# Fuppo keeps this hosting identifier to preserve https://fid.fly.dev.
app = 'fid'
primary_region = 'iad'
kill_signal = 'SIGQUIT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 200
    hard_limit = 250

  [[http_service.checks]]
    grace_period = '5s'
    interval = '30s'
    method = 'GET'
    timeout = '3s'
    path = '/healthz'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '256mb'
